default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: you_sale_dev
  pool: 5
  username: you_sale
  password: 123123

test:
  <<: *default
  database: db/you_sale_test

production:
  host: db
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: you_sale
  username: you_sale
  password: 123123
